version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - db
      - app
    networks:
      - laravel

  # Database Service
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - laravel

  # Redis Service
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - laravel

  # Application Service
  app:
    container_name: app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel

  # queue
  queue:
    container_name: queue
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/:/var/www
    working_dir: /var/www      
    command: "php artisan queue:work"
    depends_on:
        - db
        - app
        - redis
    networks:
        - laravel      

  # PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: sidneyn@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - laravel

networks:
  laravel:
    name: laravel
    driver: bridge
